{
 "title": "VoltVault_Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "HVAC Status",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iot_voltvault",
     "rawSql": "SELECT status FROM iot_voltvault.hvac_actuator ORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "HVAC Status History",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "iot_voltvault",
     "rawSql": "SELECT timestamp, status FROM iot_voltvault.hvac_actuator;"
    }
   ]
  },
  {
   "title": "Temperature [°C]",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "iot_voltvault",
     "rawSql": "SELECT timestamp, temperature FROM iot_voltvault.temphum_sensor;"
    }
   ]
  },
  {
   "title": "Humidity [%]",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "dataset": "iot_voltvault",
     "rawSql": "SELECT timestamp, temperature FROM iot_voltvault.temphum_sensor;"
    }
   ]
  },
  {
   "title": "CO Level [ppm]",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "dataset": "iot_voltvault",
     "rawSql": "SELECT timestamp, co FROM iot_voltvault.co_sensor;"
    }
   ]
  }
 ]
}